spring.datasource.url=jdbc:sqlite:dev.db
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

mybatis.type-handlers-package=io.spring.articles.infrastructure.mybatis
mybatis.mapper-locations=mapper/*.xml

logging.level.io.spring.articles.infrastructure.mybatis.readservice.ArticleReadService=DEBUG
logging.level.io.spring.articles.infrastructure.mybatis.mapper=DEBUG

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

jwt.secret=mySecretKeyForJWTTokenGenerationThatIsLongEnoughToMeetTheRequirements256Bits
jwt.sessionTime=86400
