spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/realworld}
spring.datasource.driver-class-name=${DATABASE_DRIVER:org.postgresql.Driver}
spring.datasource.username=${DATABASE_USERNAME:realworld}
spring.datasource.password=${DATABASE_PASSWORD:password}
