apiVersion: v1
kind: Secret
metadata:
  name: articles-api-secret
  namespace: default
type: Opaque
data:
  DATABASE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXM6NTQzMi9yZWFsd29ybGQ=
  DATABASE_USERNAME: cmVhbHdvcmxk
  DATABASE_PASSWORD: cGFzc3dvcmQ=
  JWT_SECRET: blJ2eVlDNHNvRnhCZFotRi01Tm56ejVVU1hzdFIxWXlsc1RkLW1BMGFLdEk5SFVscmlHcnRrZi1UaXVEYXBrTGlVQ29nTzNKT0s3a3daaXNySHA2d0E=
