server.port=8082
spring.application.name=tags-service

spring.datasource.url=jdbc:sqlite:tags.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

mybatis.configuration.cache-enabled=true
mybatis.configuration.default-statement-timeout=3000
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.use-generated-keys=true
mybatis.type-handlers-package=io.spring.tags.infrastructure.mybatis
mybatis.mapper-locations=mapper/*.xml
